site_name: Ferro's Tech Notes
site_url: https://notes.ferro.pro/

repo_url: https://github.com/fzinfz/book
edit_uri: blob/master/

exclude_docs: |
    .*
    *.rst
    *.txt
    *.sh
    /SUMMARY.md

nav:
    - Intro: README.md
    - Linux: linux/
    - Network: nw/
    - Virt: vt/
    - "*"
    - DB: db/
    - BSD: bsd/
    - Microsoft: ms/
    - Hardware: hw/
    - Elec: elec/

exclude_docs: |
    /dev/ocaml.md
    /dev/j2ee.md

theme:
    name: mkdocs
    custom_dir: custom_theme/

validation:
  nav:
    not_found: ignore
    absolute_links: ignore
  links:
    absolute_links: ignore

markdown_extensions:
  - smarty
  - sane_lists
  - toc:
        permalink: true
  - pymdownx.magiclink:

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

# https://oprypin.github.io/mkdocs-literate-nav/reference.html
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
      tab_length: 2

  - redirects:
      redirect_maps:
          'VT/README.md': 'vt/README.md'
          'web/cf.md': 'cloud/cf.md'
